### ISSUE TITLE
Numbers are not displayed in tests

### ISSUE THREAD

**Issue by marcotas** [sempro/phpunit-pretty-print#23]
Thank you so much for this amazing package. The tests are now much more beautiful and readable with CI and CD with this package.

The problem I identified is that the tests with numbers are not being displayed. Its very simple to reproduce: just create a test with a name like: `test01_it_should_do_something`.

It was expected to print like `test01 it should do something` but it is printing `test it should do something`.

We have a lot of integration tests maped with a number... It's very important thing to have in my opinion. What do you think about it? Am I missing something? Shouldn't display numbers? If yes, why?

Thank you!

**Comment by ecrmnn** [comment]
Hi
We're aware of this bug.
At the moment we do not have the time to prioritize this, but you're very welcome to submit a pull request. Please make sure the PR contains tests.

**Comment by svenluijten** [comment]
My PR would actually output `test 01 it should do something`, instead of the desired `test01 it should do something`, because it's impossible to know if you wanted the numbers to also be word boundaries (Should `test01` become `test 01` or `test01`?).

I'd be happy to hear what you want from this @marcoT89, let me know on #24 🙂
